### ISSUE TITLE
Wrong list of args in action.yml

### ISSUE THREAD

**Issue by davemaier** [okteto/destroy-stack#1]
Hi,

there seems to be a mistake in action.yml. The list of args contains the `build` arg which is not needed in this action. 
This makes arg `working-directory` unusable since the parameters for entrypoint.sh are not named but require a certain order. 

Currently `working-directory` can only be set by setting the `build` arg:

```
- name: Destroy Stack
        uses: okteto/destroy-stack@v4.2
        with:
          namespace: staging-davemaier
          name: "ava-api"
          build: "./tools/staging"
```
